---
- name: Deploy App
  hosts: app
  become: true
  tasks:
    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/Artemmkin/reddit.git'
        dest: /home/appuser/reddit
        version: monolith
      notify: restart puma
    - name: install bundler
      apt:
        name: bundler
        state: present
    - name: bundle install
      bundler:
        state: present
        chdir: /home/appuser/reddit
  handlers:
    - name: restart puma
      become: true
      systemd: name=puma state=restarted
