# Setup and configure mongodb for reddit app
- name: "Reddit App: Install mongodb"
  hosts: all
  become: yes

  tasks:
  - name: Add mongo ppa key
    apt_key: 
      keyserver: keyserver.ubuntu.com
      id: 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
 
  - name: Add APT repository
    apt_repository:
      repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
      state: present
  
  - name: Install mongodb package
    apt:
      name: mongodb-org
      state: present
      update_cache: yes
      force: yes

#    systemd: name=mongod state=restarted
    notify: restart mongod
  
  handlers:
  - name: restart mongod
    service: name=mongod state=restarted
  

